name: Dev
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GHCR_REGISTRY: ghcr.io
  DOCKERHUB_REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository_owner }}/notes
  TEST_TAG: ${{ github.repository_owner }}/notes:test

permissions:
  pull-requests: write  # for PR comments

jobs:
  test_dev:
    name: Test development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up node & dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - run: npm ci

      - name: Run the TypeScript build
        run: npx tsc

      - name: Run the unit tests
        run: npm run test
